# Generated by Django 5.2.15 on 2026-07-03 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('puerto', models.IntegerField(default=4370, help_text='Puerto TCP (4370 por defecto ZKTeco)')),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('api_key', models.CharField(help_text='Clave secreta para autenticar el dispositivo', max_length=64, unique=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Entrada principal, Sala de profesores', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispositivo Biométrico',
                'verbose_name_plural': 'Dispositivos Biométricos',
            },
        ),
        migrations.CreateModel(
            name='EventoBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_zk', models.IntegerField(help_text='ID del usuario registrado por el dispositivo')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('desconocido', 'Desconocido')], default='entrada', max_length=20)),
                ('timestamp', models.DateTimeField(help_text='Fecha/hora del marcaje según el dispositivo')),
                ('procesado', models.BooleanField(default=False, help_text='¿Ya se registró la asistencia en el sistema?')),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='biometrico.dispositivobiometrico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Biométrico',
                'verbose_name_plural': 'Eventos Biométricos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HuellaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_zk', models.IntegerField(help_text='ID numérico del usuario en el dispositivo', verbose_name='ID en ZKTeco')),
                ('template', models.TextField(blank=True, help_text='Plantilla de huella (base64)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huellas', to='biometrico.dispositivobiometrico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huellas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Huella de Docente',
                'verbose_name_plural': 'Huellas de Docentes',
                'unique_together': {('dispositivo', 'user_id_zk')},
            },
        ),
    ]
