# Generated by Django 5.2.15 on 2026-07-02 13:03

from django.db import migrations, models


def eliminar_preparatoria(apps, schema_editor):
    Grado = apps.get_model('academico', 'Grado')
    Grado.objects.filter(nivel='preparatoria').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(eliminar_preparatoria, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='grado',
            name='nivel',
            field=models.CharField(choices=[('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=50),
        ),
    ]
