# Generated by Django 5.2.15 on 2026-07-02 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('profesor', 'Profesor'), ('alumno', 'Alumno'), ('padre', 'Padre de Familia')], default='alumno', max_length=20),
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('apoderado', 'Apoderado')], default='padre', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('hijo', models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='padres', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(limit_choices_to={'rol': 'padre'}, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
                'unique_together': {('padre', 'hijo')},
            },
        ),
    ]
