# Generated by Django 5.2.15 on 2026-07-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('director', 'Director'), ('profesor', 'Profesor'), ('alumno', 'Alumno'), ('padre', 'Padre de Familia')], default='alumno', max_length=20),
        ),
    ]
