# Generated by Django 5.2.15 on 2026-07-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='titulo_profesional',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título Profesional'),
        ),
    ]
